version: '3.7'
services:
  rabbitmq3:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret cookie'
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
      - "5671:5671"
    volumes:
      - '~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/'
    networks:
      - local-network
networks:
    local-network:
        driver: bridge 